Repository GruppeX/Hockey-Project-GX-Frontend, pull requests merged in 2022-05, with the labels that each got.

#5 Create Prettify.yml
  .github/workflows/Prettify.yml
  README.md
  css/bootstrap-grid.css
  css/bootstrap-grid.min.css
  css/bootstrap-grid.rtl.css
  css/bootstrap-grid.rtl.min.css
  css/bootstrap-reboot.css
  css/bootstrap-reboot.min.css
  css/bootstrap-reboot.rtl.css
  css/bootstrap-reboot.rtl.min.css
  css/bootstrap-utilities.css
  css/bootstrap-utilities.min.css
  css/bootstrap-utilities.rtl.css
  css/bootstrap-utilities.rtl.min.css
  css/bootstrap.css
  css/bootstrap.min.css
  css/bootstrap.rtl.css
  css/bootstrap.rtl.min.css
  js/bootstrap.bundle.js
  js/bootstrap.bundle.min.js
  js/bootstrap.esm.js
  js/bootstrap.esm.min.js
  js/bootstrap.js
  js/bootstrap.min.js
Labels: Ready for Review

#6 Delete workflow.yml
  .github/workflows/workflow.yml
Labels: Ready for Review

#7 GXH-17: Added config.js to js folder, added colors and urls
  js/config.js
Labels: Ready to merge, Ready for review

#8 GXH-11 get players from db
  js/config.js
  js/players/get-players.js
Labels: Ready to merge, Ready for review

#9 Gxh 7 login page
  css/loginStyle.css
  imgg/hockeyPic.jpeg
  templates/login.html
Labels: Ready to merge

#10 Gxh 10 update player
  js/players/get-players.js
  js/update-player.js
Labels: Ready to merge

#12 GXH-6 create index frontpage
  css/bootstrap-grid.css
  css/bootstrap-grid.css.map
  css/bootstrap-grid.min.css
  css/bootstrap-grid.min.css.map
  css/bootstrap-grid.rtl.css
  css/bootstrap-grid.rtl.css.map
  css/bootstrap-grid.rtl.min.css
  css/bootstrap-grid.rtl.min.css.map
  css/bootstrap-reboot.css
  css/bootstrap-reboot.css.map
  css/bootstrap-reboot.min.css
  css/bootstrap-reboot.min.css.map
  css/bootstrap-reboot.rtl.css
  css/bootstrap-reboot.rtl.css.map
  css/bootstrap-reboot.rtl.min.css
  css/bootstrap-reboot.rtl.min.css.map
  css/bootstrap-utilities.css
  css/bootstrap-utilities.css.map
  css/bootstrap-utilities.min.css
  css/bootstrap-utilities.min.css.map
  css/bootstrap-utilities.rtl.css
  css/bootstrap-utilities.rtl.css.map
  css/bootstrap-utilities.rtl.min.css
  css/bootstrap-utilities.rtl.min.css.map
  css/bootstrap.css
  css/bootstrap.css.map
  css/bootstrap.min.css
  css/bootstrap.min.css.map
  css/bootstrap.rtl.css
  css/bootstrap.rtl.css.map
  css/bootstrap.rtl.min.css
  css/bootstrap.rtl.min.css.map
  css/player-card.css
  index.html
  js/bootstrap.bundle.js
  js/bootstrap.bundle.js.map
  js/bootstrap.bundle.min.js
  js/bootstrap.bundle.min.js.map
  js/bootstrap.esm.js
  js/bootstrap.esm.js.map
  js/bootstrap.esm.min.js
  js/bootstrap.esm.min.js.map
  js/bootstrap.js
  js/bootstrap.js.map
  js/bootstrap.min.js
  js/bootstrap.min.js.map
Labels: Ready to merge

#13 Gxh 9 delete player
  js/delete-player.js
Labels: Ready to merge

#14 Gxh 7 login page
  css/loginStyle.css
  img/Field-Hockey.png
  imgg/hockeyPic.jpeg
  templates/login.html
Labels: Ready to merge

#15 GXH-13: Added select with 3 position options
  index.html
  js/positions.js
Labels: Ready to merge, Ready for review

#16 Gxh 21 create on index
  index.html
  js/create-player.js
Labels: Ready to merge

#17 Change colors on create button
  index.html
Labels: Ready to merge

#18 Gxh 12 search for player
  css/style.css
  index.html
  js/create-player.js
  js/players/get-players.js
  js/players/select-player.js
Labels: Ready to merge

#19 Gxh 15 index page 11 players
  index.html
  js/players/select-player-on-card.js
  js/players/select-player.js
  js/positions.js
Labels: Ready to merge

#20 Only on push to master its get pretty
  .github/workflows/Prettify.yml
Labels: Ready for review

#21 GXH-14 create position view
  css/hockey-field.css
  css/style.css
  index.html
  js/config.js
  js/players/select-player-on-card.js
  js/positions.js
Labels: Ready to merge, Ready for review

#22 Update Prettify.yml
  .github/workflows/Prettify.yml
  css/hockey-field.css
  index.html
  js/players/select-player-on-card.js
  js/positions.js
Labels: Ready to merge, Ready for review

#23 Gxh 19 make a nice readme frontend md file
  README.md
Labels: Ready to merge

#24 change contact and typo
  README.md
Labels: Ready to merge

#25 GXH-34 changed color to lighter blue after request from product owner
  css/hockey-field.css
Labels: Ready to merge

#26 GXH-32 size fixed on cards so all initials show
  css/hockey-field.css
Labels: Ready to merge

#27 GXH-33: now i remove all childrens befor adding all again
  js/players/select-player.js
Labels: Ready to merge, Ready for review

#29 Gxh 33 fix search to too many
  js/players/select-player.js
Labels: Ready to merge

#30 Gxh 35 border on playercards
  index.html
  js/players/select-player-on-card.js
  js/players/select-player.js
Labels: Ready to merge

#33 Gxh 24 only login shows
  index.html
  js/login.js
  templates/login.html
Labels: Ready to merge, Ready for review

#31 create-player-now-with-JSDoc
  js/create-player.js
Labels: Ready to merge, Ready for review

#32 Gxh 20 update on index
  index.html
  js/players/get-players.js
  js/players/select-player-on-card.js
  js/update-player.js
Labels: Ready to merge

#34 Gxh 22 delete player
  .github/workflows/approvedLabel.yml
  .prettierignore
  .prettierrc.json
  index.html
  js/delete-player.js
  js/players/delete-player.js
  js/players/select-player.js
  package-lock.json
  package.json
Labels: Ready to merge
